# Generated by Django 3.2.14 on 2022-08-24 09:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('record_id', models.UUIDField(default=uuid.UUID('f8ab2c25-0fa1-4853-8be7-8f3abc61093f'), editable=False, primary_key=True, serialize=False)),
                ('record_progress', models.IntegerField(null=True)),
                ('record_type', models.IntegerField(choices=[(1026, 'KDM'), (1027, 'DCP'), (1028, 'SPL'), (1029, 'PACK'), (1030, 'RAR')], default=1026)),
                ('record_annotation', models.CharField(max_length=200, null=True)),
                ('record_theatre', models.CharField(max_length=200, null=True)),
                ('record_datetime', models.CharField(max_length=100, null=True)),
                ('record_status', models.IntegerField(choices=[(-1, 'PENDING'), (0, 'QUEUED'), (1, 'IN_PROGRESS'), (2, 'IN_PROGRESS_POST'), (3, 'PAUSED'), (4, 'FINISHED'), (5, 'CANCELED'), (6, 'EXCEPTION')], default=-1)),
                ('record_exception_messages', models.CharField(max_length=2000, null=True)),
            ],
            options={
                'db_table': 'record',
            },
        ),
    ]
