# Generated by Django 3.2.14 on 2022-08-23 15:44

from django.db import migrations
import json


def data_import(apps, schema_editor):
    Record = apps.get_model("transfer_record", "Record")

    objects = open('transfer_record/static/test.json')
    data = json.load(objects)

    for i in data['objects']:
        Record.objects.create(
            record_id=i['id'],
            record_progress=i['progress'],
            record_type=i['type'],
            record_annotation=i['annotation'],
            record_theatre=i['theatre'],
            record_datetime=i['datetime'],
            record_status=i['status'],
            record_exception_messages=i['messages'][0]
        )


class Migration(migrations.Migration):

    dependencies = [
        ('transfer_record', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(data_import),
    ]
